version: '3.9'

## VARIABLES
# $USER
# $TZ
# $PUID
# $PGID
# $USERDIR
# $DOCKERDIR
# $MEDIADIR

# $DOMAINNAME
# $OPENVPN_PROVIDER
# $OPENVPN_USERNAME
# $OPENVPN_PASSWORD
# $CLOUDFLARE_EMAIL
# $CLOUDFLARE_API_KEY
# $CLOUDFLARE_API_KEY
# $BASIC_AUTH_USER
# $BASIC_AUTH_PASS
# $EUFY_USER
# $EUFY_PASS
# $LIBRESPEED_PASS
# $PICOSHARE_PASS

########################### EXTENSION FIELDS
# Helps eliminate repetition of sections

# Common environment values
x-environment: &default-tz-puid-pgid
  TZ: $TZ
  PUID: $PUID
  PGID: $PGID

# Proxy Network and Security
x-network-and-security: &network-and-security
  networks:
    - proxy
  security_opt:
    - no-new-privileges:true

# Keys common to some of the dependent services/apps
x-common-keys-apps: &common-keys
  <<: *network-and-security
  restart: unless-stopped

  
######################### SERVICES

services:

  ########################### Home Assistant
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - $DOCKERDIR/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    privileged: true
    network_mode: host
    # networks:
    #   - proxy
    ports:
      - 8123:8123
    healthcheck:
      test: "curl --connect-timeout 10 --silent -f http://127.0.0.1:8123/ || exit 1"
      interval: 45s
      timeout: 30s
      retries: 3
    # devices:
    #  - /dev/ttyUSB0:/dev/ttyUSB0
      
  ########################### Nginx Proxy Manager
  nginx-proxy-manager:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx-proxy-manager
    <<: *common-keys # See EXTENSION FIELDS at the top
    restart: unless-stopped
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
    volumes:
      - $DOCKERDIR/npm/data:/data
      - $DOCKERDIR/npm/letsencrypt:/etc/letsencrypt

  ########################### AUTOHEAL
  autoheal:
    image: willfarrell/autoheal:latest
    tty: true
    container_name: autoheal
    <<: *common-keys # See EXTENSION FIELDS at the top
    restart: always
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  ########################### WatchTower
  watchtower:
    container_name: watchtower
    <<: *common-keys # See EXTENSION FIELDS at the top
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  ########################### Heimdall  
  heimdall:
    image: ghcr.io/linuxserver/heimdall
    container_name: heimdall
    environment:
      <<: *default-tz-puid-pgid
    volumes:
      - $DOCKERDIR/heimdall:/config
    ports:
      - 8500:80
      # - 8600:443
    <<: *common-keys # See EXTENSION FIELDS at the top

  ########################### LibreSpeed
  librespeed:
    image: linuxserver/librespeed
    container_name: librespeed
    environment:
      <<: *default-tz-puid-pgid
      PASSWORD: $LIBRESPEED_PASS
    volumes:
      - $DOCKERDIR/librespeed:/config
    ports:
      - 8383:80
    restart: unless-stopped
    
  ########################### Dozzle
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # ports:
    #   - 9999:8080
    <<: *common-keys # See EXTENSION FIELDS at the top


  ########################### Node Red
  node-red:
    image: nodered/node-red:latest
    container_name: nodered
    environment:
      - TZ=$TZ
    <<: *common-keys # See EXTENSION FIELDS at the top
    volumes:
      - $DOCKERDIR/node-red:/data
    ports:
      - 1880:1880

  ########################### Mosquitto
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    restart: unless-stopped
    network_mode: host
    volumes:
      - $DOCKERDIR/mosquitto/:/mosquitto/


  ########################### Transmission OpenVPN
  transmission-openvpn:
    container_name: transmission
    cap_add:
        - NET_ADMIN
    volumes:
        - '$DOCKERDIR/transmission/data:/data'
        - '$DOCKERDIR/transmission/config:/config'
        - '$DOCKERDIR/transmission/downloads/:/data/completed'
        - '$DOCKERDIR/transmission/downloads/:/downloads'
    environment:
      <<: *default-tz-puid-pgid
      OPENVPN_PROVIDER: $OPENVPN_PROVIDER
      OPENVPN_USERNAME: $OPENVPN_USERNAME
      OPENVPN_PASSWORD: $OPENVPN_PASSWORD
      NORDVPN_COUNTRY: RO
      NORDVPN_CATEGORY: Europe
      NORDVPN_PROTOCOL: tcp
      LOCAL_NETWORK: 192.168.0.0/16
      TRANSMISSION_HOME: /config/transmission-home
      TRANSMISSION_DOWNLOAD_DIR: /downloads
      TRANSMISSION_WATCH_DIR: /data/watch
      TRANSMISSION_INCOMPLETE_DIR: /downloads/incomplete
      TRANSMISSION_RATIO_LIMIT_ENABLED: "true"
      TRANSMISSION_RATIO_LIMIT: 1
      TRANSMISSION_IDLE_SEEDING_LIMIT_ENABLED: "true"
      TRANSMISSION_IDLE_SEEDING_LIMIT: 1
    logging:
        driver: json-file
        options:
            max-size: 10m
    <<: *common-keys # See EXTENSION FIELDS at the top
    image: haugene/transmission-openvpn

  ########################### Prowlarr
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      <<: *default-tz-puid-pgid
    volumes:
      - $DOCKERDIR/prowlarr:/config
    ports:
      - 9696:9696
    <<: *common-keys # See EXTENSION FIELDS at the top

  ########################### Bazarr
  bazarr:
    image: ghcr.io/linuxserver/bazarr
    container_name: bazarr
    environment:
      <<: *default-tz-puid-pgid
    volumes:
      - $DOCKERDIR/bazarr:/config
      - $MEDIADIR/movies:/movies
      - $MEDIADIR/tv:/tv
    ports:
      - 6767:6767
    <<: *common-keys # See EXTENSION FIELDS at the top

  ########################### Sonarr
  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      <<: *default-tz-puid-pgid
    volumes:
      - $DOCKERDIR/sonarr:/config
      - $MEDIADIR/tv:/tv
      - $DOCKERDIR/transmission/downloads:/downloads
    ports:
      - 8989:8989
    <<: *common-keys # See EXTENSION FIELDS at the top

  ########################### Radarr
  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    environment:
      <<: *default-tz-puid-pgid
    volumes:
      - $DOCKERDIR/radarr:/config
      - $MEDIADIR/movies:/movies
      - $DOCKERDIR/transmission/downloads:/downloads
    ports:
      - 7878:7878
    <<: *common-keys # See EXTENSION FIELDS at the top

  ########################### Scrutiny
  scrutiny:
    image: ghcr.io/analogj/scrutiny:master-omnibus
    container_name: scrutiny
    cap_add:
      - SYS_RAWIO
      - SYS_ADMIN #optional
    environment:
      # <<: *default-tz-puid-pgid
      SCRUTINY_API_ENDPOINT: "https://scrutiny.local.szaszattila.com"
      # SCRUTINY_WEB: "true"
      SCRUTINY_COLLECTOR: "true"
    volumes:
      - $DOCKERDIR/scrutiny:/opt/scrutiny/config
      - $DOCKERDIR/influxdb/data:/opt/scrutiny/influxdb
      - /run/udev:/run/udev:ro
    ports:
      - 8088:8080
    devices:
      - /dev/sda:/dev/sda
      - /dev/nvme0n1:/dev/nvme0n1
    <<: *common-keys # See EXTENSION FIELDS at the top
    
  ########################### PicoShare
  picoshare:
    image: mtlynch/picoshare
    environment:
      - PORT=3001
      - PS_SHARED_SECRET=$PICOSHARE_PASS
    ports:
      - 3001:3001
    command: -db /data/store.db
    volumes:
      - $DOCKERDIR/picoshare:/data
      
######################### NETWORKS
networks:
  proxy:
    external: true