version: '3.9'

######################### SERVICES

services:

  ####################### AUTOHEAL
  autoheal:
    image: willfarrell/autoheal:latest
    tty: true
    container_name: autoheal
    restart: always
    environment:
      - AUTOHEAL_CONTAINER_LABEL=all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

######################### NETWORKS
networks:
  proxy:
    external: true
    