version: '3.9'

## VARIABLES - Make sure you create these in Portainer as environment variables, or in a file named ".env" next to the docker-compose file
# $DOCKERDIR --- Where you want to map your Docker volumes

########################### EXTENSION FIELDS
# Helps eliminate repetition of sections

# Keys common to some of the dependent services/apps
# Create the network beforehand, as bridge
x-common-keys-apps: &common-keys
  networks:
    - synny
  security_opt:
    - no-new-privileges:true
  restart: unless-stopped

######################### SERVICES
services: 

  ########################### POSTGRES
  wikijs-db:
    image: postgres:15-alpine
    container_name: wikijs-db
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    volumes:
      - $DOCKERDIR/wikijs:/var/lib/postgresql/data
    <<: *common-keys
    
  ########################### WIKIJS
  wiki:
    image: ghcr.io/requarks/wiki:2
    container_name: wikijs
    depends_on:
      - wikijs-db
    environment:
      DB_TYPE: postgres
      DB_HOST: wikijs-db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: $POSTGRES_PASSWORD
      DB_NAME: wiki
    ports:
      - "88:3000"  
    volumes:
      - $DOCKERDIR/wikijs/backups:/backups
    <<: *common-keys
    
######################### NETWORKS
# Create this network before deploying the services, either in Portainer or with a docker command 
networks:
  synny:
    external: true
    