version: '3.9'

## VARIABLES - Make sure you create these in Portainer as environment variables, or in a file named ".env" next to the docker-compose file
# $USER --- Linux user
# $TZ --- Timezone. Example: "Europe/Bucharest"
# $PUID --- Value of uid from the linux "id" command. Usually 1000
# $PGID --- Value of gid from the linux "id" command. Usually 1000
# $DOCKERDIR --- Where you want to map your Docker volumes
# $LIBRESPEED_PASS
# $PICOSHARE_PASS

########################### EXTENSION FIELDS
# Helps eliminate repetition of sections

# Common environment values
x-environment: &default-tz-puid-pgid
  TZ: $TZ
  PUID: $PUID
  PGID: $PGID

# Keys common to some of the dependent services/apps
# Create the network beforehand, as bridge
x-common-keys-apps: &common-keys
  networks:
    - synny
  security_opt:
    - no-new-privileges:true
  restart: unless-stopped

######################### SERVICES
services: 

  ########################### GUACAMOLE
  guacamole:
    image: flcontainers/guacamole
    container_name: guacamole
    environment:
      <<: *default-tz-puid-pgid
      EXTENSIONS: 'auth-totp'
    volumes:
      - postgres:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8080:8080
    <<: *common-keys
    
  ########################### PIHOLE
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    networks:
      - synny
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "81:80/tcp"
    environment:
      TZ: $TZ
      WEBPASSWORD: $PIHOLE_PASS
    volumes:
      - $DOCKERDIR/pihole/data:/etc/pihole
      - $DOCKERDIR/pihole/etc-dnsmasq.d:/etc/dnsmasq.d
    cap_add:
      - NET_ADMIN
      - SETUID
      - SETGID
    restart: unless-stopped
    
  ########################### Homepage
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    ports:
      - 3000:3000
    volumes:
      - $DOCKERDIR/homepage:/app/config
      - $DOCKERDIR/homepage/icons:/app/public/icons
      - /var/run/docker.sock:/var/run/docker.sock
    <<: *common-keys

  ########################### LibreSpeed
  librespeed:
    image: linuxserver/librespeed
    container_name: librespeed
    environment:
      <<: *default-tz-puid-pgid
      PASSWORD: $LIBRESPEED_PASS
    volumes:
      - $DOCKERDIR/librespeed:/config
    ports:
      - 8383:80
    restart: unless-stopped
    <<: *common-keys   

  ########################### PicoShare
  picoshare:
    image: mtlynch/picoshare
    container_name: picoshare
    environment:
      - PORT=3001
      - PS_SHARED_SECRET=$PICOSHARE_PASS
    ports:
      - 3001:3001
    command: -db /data/store.db
    volumes:
      - $DOCKERDIR/picoshare:/data
    <<: *common-keys

  ########################### HomeBox
  homebox:
    image: ghcr.io/hay-kot/homebox:latest
    container_name: homebox
    environment:
    - HBOX_LOG_LEVEL=info
    - HBOX_LOG_FORMAT=text
    - HBOX_WEB_MAX_UPLOAD_SIZE=10
    - HBOX_OPTIONS_ALLOW_REGISTRATION=false
    volumes:
      - homebox-data:/data/
    ports:
      - 3100:7745
    <<: *common-keys # See EXTENSION FIELDS at the top
    
######################### NETWORKS
# Create this network before deploying the services, either in Portainer or with a docker command 
networks:
  synny:
    external: true
    
######################### VOLUMES
volumes:
   homebox-data:
     driver: local
   postgres:
     driver: local     